DB:
  SSLMode: disable
  MaxOpenConns: 10
  MaxIdleConns: 10
  ConnMaxLifetime: 5m

JWTExpiration : 1h
RefreshTokenExpiration : 24h

AdminUser:
  Username: admin
  Name: "Danuwat Baongoen"
  Password: Kmutnb@Eng

Devices:
  USB: COM7 # /dev/ttyUSB0
  BaudRate: 9600 # 2400
  DataBits: 8
  StopBits: 1
  Parity: "N"
  Timeout: 1
  LoopReadTime: 1
  LoopbroadcastTime: 2
  LoopRecordTime: 5
  DEVICE01:  # ถ้าเปลี่ยนการตั้งค่า Device เช่น DeviceId, Name ให้ลบ device_masters ก่อน start server 
    SlaveId: 227
    DeviceId: "DEVICE-01"
    Name: "Device 01"
  DEVICE02: 
    SlaveId: 1
    DeviceId: "DEVICE-02"
    Name: "Device 02"
  DEVICE03: 
    SlaveId: 2
    DeviceId: "DEVICE-03"
    Name: "Device 03"